name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create draft release
    runs-on: ubuntu-20.04
    outputs:
      upload_url: ${{steps.create_release.outputs.upload_url}}

    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: ${{ contains(github.ref, '-rc.') }}

  build:
    name: Build and publish release asset
    runs-on: ubuntu-20.04
    needs: release
    steps:
      - uses: actions/checkout@v3

      - name: Validate version
        run: |
          VERSION="v$(cat VERSION)"
          if [[ "$TAG" != "$VERSION" ]]; then
              echo "VERSION does not match commit tag"
              exit 1
          fi
        env:
          TAG: ${{ github.ref }}

      - name: Set up BEAM
        uses: erlef/setup-beam@v1
        with:
          elixir-version: 1.14.x
          otp-version: 25.x

      - name: Install dependencies
        run: mix deps.get

      - name: Build release
        run: |
          mix elixir_ls.release2 -o ./release
          zip -jr elixir-ls.zip ./release

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./elixir-ls.zip
          asset_name: elixir-ls-${{ github.ref }}.zip
          asset_content_type: application/zip
